# Generated by Django 3.2.3 on 2021-06-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='books.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Costumer_Email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField(default=0)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.order')),
            ],
        ),
    ]
